services:
  db:
    image: postgres:17-alpine
    container_name: forumate-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forumate
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: forumate-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata:
    external: true
    name: backend_pgdata
