export const memberErrorCodes = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  INVALID_MEMBER_USERNAME: 'INVALID_MEMBER_USERNAME',
  INSUFFICIENT_MEMBER_LEVEL: 'INSUFFICIENT_MEMBER_LEVEL',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  MEMBER_USERNAME_ALREADY_EXISTS: 'MEMBER_USERNAME_ALREADY_EXISTS',
  INVALID_REPUTITION_LEVEL: 'INVALID_REPUTITION_LEVEL',
} as const;

export type MemberErrorCode =
  (typeof memberErrorCodes)[keyof typeof memberErrorCodes];
